service: starlightserverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-2

functions:
  handler:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any